Repository Axway/streams-open-docs, pull requests merged in 2021-12, with the labels that each got.

#132 STREAMS-2399 Add alternate installation settings section
  .gitignore
  content/en/docs/install/_index.md
  content/en/docs/install/backup-recovery.md
  content/en/docs/install/customize-install.md
  content/en/docs/install/helm-parameters-reference.md
  content/en/docs/install/uninstall.md
  content/en/docs/install/upgrade.md
  content/en/docs/metrics.md
  content/en/docs/relnotes/20211130_streams_relnotes.md
Labels: size/l, February 22

#134 STREAMS-2399 Add heading to manage helm parameters
  content/en/docs/install/customize-install.md
Labels: size/xs, February 22

#133 STREAMS-1415 - Describe how to run smoke tests after the installation
  content/en/docs/install/_index.md
Labels: size/s, February 22
