Repository Axway/streams-open-docs, pull requests merged in 2021-08, with the labels that each got.

#109 STREAMS-2132 Update nginx version
  content/en/docs/architecture/_index.md
  content/en/docs/relnotes/20210820_streams_relnotes.md
Labels: size/s

#111 STREAMS-2177 add websocket subscriber documentation
  content/en/docs/relnotes/20210827_streams_relnotes.md
  content/en/docs/subscribers/_index.md
  content/en/docs/subscribers/subscriber-kafka.md
  content/en/docs/subscribers/subscriber-sse.md
  content/en/docs/subscribers/subscriber-webhook.md
  content/en/docs/subscribers/subscriber-websocket.md
Labels: size/m

#113 STREAMS-2173 upgrade kafka version
  content/en/docs/architecture/_index.md
Labels: size/xs

#114 STREAMS-1868 explain how to encrypt Kafka data at rest
  content/en/docs/architecture/_index.md
Labels: size/xs
