Repository Axway/streams-open-docs, pull requests merged in 2021-06, with the labels that each got.

#95 RDAPI-24501 Update JSON packages to fix Netlify deploys
  package-lock.json
  package.json
Labels: dependencies

#101 Adding Pull Request size labeler to the project
  .github/workflows/labeler.yml
Labels: size/s

#94 STREAMS-1921 Add Disaster Recovery Plan procedures
  content/en/docs/install/backup-recovery.md
Labels: Needs more information, size/m

#100 STREAMS-1734 document Streams metrics to monitor
  content/en/docs/install/backup-recovery.md
  content/en/docs/metrics.md
Labels: size/s

#102 STREAMS-2090 Update ingress annotations parameters and Add info about double quotation marks usage
  content/en/docs/install/_index.md
  content/en/docs/install/helm-parameters.md
Labels: size/s

#103 STREAMS-2000 Add HTTP Poller and HTTP Post performance tests results
  content/en/docs/capacity/performance_tests_settings.md
Labels: size/m

#104 Final review, tide up, and minor fixes in preparation for Streams June 21 release
  content/en/docs/install/_index.md
  content/en/docs/install/helm-parameters.md
  content/en/docs/relnotes/20210618_streams_relnotes.md
Labels: size/m

#106 STREAMS-2098 Add nodeSelector parameter for Nginx default backend
  content/en/docs/architecture/_index.md
Labels: size/xs
